# Github Actions CI/CD
---
name: Checks #Workflow 이름

on: [push] # git push 이벤트 활성화 -> 리포지토리에 푸쉬 했을 때 활성화

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-22.04
    steps:
     - name: Login in to Docker Hub
       uses: docker/login-action@v1
       with:
         username: ${{ secrets.DOCKERHUB_USER }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Check out # 깃헙 코드를 작업환경으로 가져오는 역할
       uses: actions/checkout@v2
     - name: Run Test Ccode
       run: docker-compose run --rm app sh -c 'python manage.py test'
     - name: Run Flake8 for Lint Check
       run: docker-compose run --rm app sh -c 'flake8'




